import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Use — Energy Advocate',
  description: 'Terms of use, disclaimer, and legal information for Energy Advocate.',
};

export default function TermsPage() {
  const year = new Date().getFullYear();

  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="sticky top-0 z-10 bg-white/90 backdrop-blur border-b border-slate-100 shadow-sm">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 text-slate-900 hover:text-amber-500 transition-colors">
            <SunIcon className="w-5 h-5 text-amber-400" />
            <span className="font-bold text-base tracking-tight">Energy Advocate</span>
          </Link>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-4 sm:px-6 py-14 sm:py-20">
        <p className="text-xs font-semibold text-slate-400 uppercase tracking-widest mb-3">Legal</p>
        <h1 className="text-3xl font-black text-slate-900 tracking-tight mb-2">Terms of Use</h1>
        <p className="text-sm text-slate-400 mb-10">Last updated: May {year}</p>

        <div className="prose prose-slate prose-sm max-w-none space-y-8">

          <section>
            <h2 className="text-base font-bold text-slate-900 mb-2">1. Informational Purpose Only</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              Energy Advocate provides solar assessment data for informational purposes only. Nothing on this site constitutes financial, tax, legal, or engineering advice. All estimates — including system output, savings projections, payback periods, and cost ranges — are approximations based on publicly available government data and industry benchmarks. Actual results will vary based on your specific property, installer, local utility rates, weather, and other factors.
            </p>
            <p className="text-sm text-slate-600 leading-relaxed mt-2">
              Always consult a licensed solar contractor, tax professional, and your local utility before making any purchase decision.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-slate-900 mb-2">2. No Warranties</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              This service is provided "as is" without warranties of any kind, express or implied. We do not warrant the accuracy, completeness, or fitness for any particular purpose of any data, estimate, or output generated by this tool. We are not responsible for any decisions made in reliance on information from this site.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-slate-900 mb-2">3. No Affiliation with Installers</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              Energy Advocate is fully independent. We have no financial relationship with any solar installer, equipment manufacturer, financing company, or lead generation service. We do not sell, share, or monetize your address or any other information you enter. No data you submit is stored on our servers.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-slate-900 mb-2">4. Permitted Use</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              You may use this tool for personal, non-commercial research about your own property. The following uses are prohibited:
            </p>
            <ul className="mt-2 space-y-1 text-sm text-slate-600 pl-4">
              <li className="flex gap-2"><span className="text-slate-300 flex-shrink-0">—</span> Automated or programmatic access (scraping, bots, scripts)</li>
              <li className="flex gap-2"><span className="text-slate-300 flex-shrink-0">—</span> Commercial resale or redistribution of assessments or data outputs</li>
              <li className="flex gap-2"><span className="text-slate-300 flex-shrink-0">—</span> Use by solar installers or lead generation companies to pre-qualify prospects without homeowner consent</li>
              <li className="flex gap-2"><span className="text-slate-300 flex-shrink-0">—</span> Any use that violates applicable law</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-slate-900 mb-2">5. Third-Party Data Sources</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              This tool pulls data from Google Solar API, NREL PVWatts, NREL Utility Rates, the U.S. Energy Information Administration (EIA), and DSIRE. We are not affiliated with any of these organizations. Data availability and accuracy depend on the coverage and update frequency of those services, which is outside our control.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-slate-900 mb-2">6. Intellectual Property</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              All source code, design, written content, and product logic comprising Energy Advocate are the exclusive property of Energy Advocate and its owner. "Energy Advocate" is a trademark. Reproduction, modification, reverse engineering, or commercial use of any part of this product without express written permission is prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-slate-900 mb-2">7. Limitation of Liability</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              To the maximum extent permitted by law, Energy Advocate and its owner shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of this tool or reliance on any data it produces — including but not limited to lost profits, solar system underperformance, or adverse tax outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-slate-900 mb-2">8. Changes to These Terms</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              We may update these terms at any time. Continued use of the site after changes are posted constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-slate-900 mb-2">9. Contact</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              Questions about these terms? Contact us at{' '}
              <a href="mailto:legal@energyadvocate.app" className="text-amber-600 hover:underline">
                legal@energyadvocate.app
              </a>
            </p>
          </section>

        </div>

        <div className="mt-14 pt-8 border-t border-slate-100 flex items-center justify-between text-xs text-slate-400">
          <p>© {year} Energy Advocate™. All rights reserved.</p>
          <Link href="/" className="hover:text-amber-500 transition-colors">← Back to assessment</Link>
        </div>
      </main>
    </div>
  );
}

function SunIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.227-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0z" />
    </svg>
  );
}
